### ISSUE TITLE
test issue request

### ISSUE THREAD

**Issue by naoki000** [shotammm/ABC#1]
私も使い方そんな知らないから試しにコメント

https://github.com/shotammm/ABC/blob/804db348ebd51322c308756b733c93a982cf6768/ABC144-E.py#L35

ここさっき送ってもらったものと違うけどこれがあってるん？

**Comment by shotammm** [comment]
いや分からん。そこ何が正解か分からなくてあれこれ試してる。
関数checkはある0からある整数xまではFalse、それより大きい整数はTrueって返ってくるんですけど、それで返る最小の整数xを求めたいのね。
で、二分探索を試みてるんですけど（0~10**12で。10**12がxの最大値）、最後どうやってxを導出すればいいか分からんっていう。

**Comment by naoki000** [comment]
left = -1 //※1
right = 10**12+1

while left <= right:
    center = (left+right)//2
    if check(center) == True:
        right = center //※2
    else:
        left = center //※2

    if left + 1  >= right: //※3
        print(right)
        exit()

（もう分からんから答えの動画みたけど）変更点は以下の二点
※1 leftの初期値は-1 -> leftとrightは外れる値（0はだめ）を初期値に設定する必要がある
※2 right と leftはcenterを代入
※3 終わる条件は、leftに+1したときに、right以上になるとき -> leftとrightがとなり合った時も終了

でどう？
なにも説明できんくてすまん。。

**Comment by naoki000** [comment]
right = center-1

        left = center+1

ちなみにこれなんで-1 +1 してるん？
centerに入れないと変にずれてしまうんやけど

**Comment by naoki000** [comment]
ちなみに
whileはleft +1 がrightより小さい間ループすればいいからこれでもいけそう

while left +1  < right:
    center = (left+right)//2
    if check(center) == True:
        right = center
    else:
        left = center

print(right)

**Comment by shotammm** [comment]
> ちなみにこれなんで-1 +1 してるん？
> centerに入れないと変にずれてしまうんやけど
確かに！不要であった

> ※3 終わる条件は、leftに+1したときに、right以上になるとき -> leftとrightがとなり合った時も終了
答えが2の時と3の時でずれたりするかな？最後±1の数字取っちゃいそう、的なことを考えてたけど確かにright取ればいいね！azs

**Comment by shotammm** [comment]
`right = 10**12`
か、答えが10**12の時にright=10**12+1でexitしないように
